### ISSUE TITLE
TeamEngine beta with XML parser error javax.xml.parsers.FactoryConfigurationError: Provider org.apache.xerces.jaxp.DocumentBuilderFactoryImpl not found

### ISSUE THREAD

**Issue by bangph** [opengeospatial/ets-wcs20#109]
I've tested WCS 2.0.1 core standard with this endpoint http://conformance.rasdaman.com/rasdaman/ows?service=WCS&version=2.0.1&request=GetCapabilities

on teamengine beta  http://cite.opengeospatial.org/te2/viewOldSessionLog.jsp?session=s0108

It failed in some test cases, I wanted to look at the log by clicking on "View Details"

![image](https://user-images.githubusercontent.com/6914451/161888539-f2b59121-0cc9-4c5d-a5bd-42a99664bcdd.png)

Then, it opens a new page  with errors

- e.g.

http://cite.opengeospatial.org/te2/viewTestLog.jsp?test=s0108/d13242e65_1/d13242e193_1/d14560e64_1/d14174e30_1

![image](https://user-images.githubusercontent.com/6914451/161888615-b09d016b-00cd-4d95-8f27-d93197542287.png)

- e.g.

http://cite.opengeospatial.org/te2/viewTestLog.jsp?test=s0108/d13242e65_1/d13242e193_1/d14560e73_1/d14707e28_1

![image](https://user-images.githubusercontent.com/6914451/161888699-3d19381f-09a0-4a4f-8928-5b1d2868998a.png)

Strangely, even with succeed tests, when I click on "View Details", it also has error

- e.g.

http://cite.opengeospatial.org/te2/viewTestLog.jsp?test=s0108/d13242e65_1/d13242e193_1/d14560e64_1/d14174e18_1

![image](https://user-images.githubusercontent.com/6914451/161888809-c3371daf-9884-434b-9a60-a6f0d467a411.png)

**Comment by bangph** [comment]
@dstenger  It seems the old style results report has this problem only.

**Comment by dstenger** [comment]
Thank you for reporting. We will do further investigation.

I am able to reproduce the problem on te2. I realized that the problem does not occur on Production.
Also, I tried to reproduce the problem on a locally running instance of Beta and the problem does not occur.
We have to check why the problem occurs on te2.

I just restarted te2 and now the problem seems to be gone. @bangph Can you please check this?
However, we will do further analysis why the problem occurred in the first place.
