### ISSUE TITLE
Test get-kvp-core-req41 is failing on Beta environment

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wcs20#113]
**Describe the bug**
Test get-kvp-core-req41 is failing on Beta environment. No error message is printed and all sub-tests are passing.

This failure is not occurring on Production environment although on both environments test suite version 1.17 is running.

So, the failure might be related to the update of the TEAM Engine version (5.5.2) on Beta.

**To Reproduce**
1. Go to https://cite.ogc.org/te2/.
2. Execute WFS 2.0 test suite with endpoint http://ows.eox.at/cite/mapserver?service=WCS&version=2.0.1&request=GetCapabilities.
3. View result of test get-kvp-core-req41.

**Expected behavior**
It is expected that get-kvp-core-req41 is passing on Beta environment as well (or at least an error message shall be printed).

**Comment by bpross-52n** [comment]
This is what I found out:
Actually, the test should also fail on production. At least one of the subtests fails.
This [request](http://ows.eox.at/cite/mapserver?request=GetCoverage&coverageid=MER_FRS_1PNUPA20090701_124435_000005122080_00224_38354_6861_RGB&service=WCS&VERSION=2.0.1&subset=dimension_bogus(-36.1114206)) for example should return an exception containing 'InvalidAxisLabel', which it does not.
So it is an inheritance issue. The behavior of the current beta is at least more correct, imho. The problem is, that each subtest calls another test first (see [here](https://github.com/opengeospatial/ets-wcs20/blob/5f6c9744e4a5e5524f2b3975432074fa5ac6c362/src/main/scripts/ctl/GetCoverage.xml#L2099), and [here](https://github.com/opengeospatial/ets-wcs20/blob/5f6c9744e4a5e5524f2b3975432074fa5ac6c362/src/main/scripts/ctl/GetCoverage.xml#L2132)) checking for the correct status code. This test passes and the following checks for the exception text (see [here](https://github.com/opengeospatial/ets-wcs20/blob/5f6c9744e4a5e5524f2b3975432074fa5ac6c362/src/main/scripts/ctl/GetCoverage.xml#L2103)) are somehow not taken into account. One quick solution would be to put both checks (statuscode and exception text) in one test. But we should probably have another look at the inheritance, especially with nested tests.

**Comment by dstenger** [comment]
Next steps:
- Create unit tests in TEAM Engine to reproduce the failure.
- Fix the problem either in TEAM Engine or by refactoring the test suite.

**Comment by dstenger** [comment]
An issue was created for TEAM Engine: https://github.com/opengeospatial/teamengine/issues/560
