### ISSUE TITLE
Validate the service endpoint URL before running test

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wcs20#49]
See https://github.com/opengeospatial/teamengine/issues/214.

**Comment by keshav-nangare** [comment]
We have two way to provide the capability doc to test i.e. 
1. URL 
2. Capability document[File],
So we can't do URL as mandatory field so I removing this attribute from this.

Updated:  `<input type="url" name="url" size="100" pattern="[a-z]{3,}://.+" />`

I have added the pattern attribute to cover some validation scenarios.

**Comment by keshav-nangare** [comment]
Fixed with this commit: ecfa272

**Comment by lgoltz** [comment]
Successfully tested locally within docker environment and the following URLs:
 * http://moon.planetserver.eu:8084/rasdaman/ows?service=WCS&request=GetCapabilities&acceptversions=2.0.1
   * Test is executed and has expected results
 * https://moon.planetserver.eu:8084/rasdaman/ows?service=WCS&request=GetCapabilities&acceptversions=2.0.1
   * Test is executed and fails because the service is not available
 * moon.planetserver.eu:8084/rasdaman/ows?service=WCS&request=GetCapabilities&acceptversions=2.0.1
   * Test is not executed, an hint is shown that a the input is not expected.
* file:///tmp/capabilities.xml
   * Test is executed and fails as a file url is not expected
