### ISSUE TITLE
If all conformance classes are selected, HTML report is not generated correctly

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wcs20#67]
Tested service: http://ows.eox.at/cite/mapserver?service=wcs&version=2.0.1&request=getcapabilities

7 conformance classes are tested.

Only one conformance class is shown in HTML report (```main_test```).
Screenshot of part of HTML report:

![ets-wcs20-html-report](https://user-images.githubusercontent.com/2989166/40185581-3695539a-59f3-11e8-8fa6-b934db320fb3.png)

**Comment by dstenger** [comment]
@keshav-nangare Can you please analyse this issue?

**Comment by keshav-nangare** [comment]
@dstenger 

I have tested the wcs20 test with the latest teamengine master but giving the correct result.

I have selected only two conformance classes main_test and post-xml-main and report generated accordingly.

Here is screenshot:

![image](https://user-images.githubusercontent.com/14732650/40237047-ed9da310-5acc-11e8-9226-debc7e25c3d2.png)


Can you please provide more details to reporduce this issue?

**Comment by dstenger** [comment]
@keshav-nangare 

Please select all conformance classes to reproduce this bug.
Can you also test this issue on beta web site [1] (was just updated)?

[1] http://cite.opengeospatial.org/te2/

**Comment by keshav-nangare** [comment]
The result page is displaying the weired HTML report because of the some HTML tags are missing so the content get mixed in this page. The xslt is falied in the middle while generating the report.

We get the following error while generating the HTML report:

```
Error on line 301 of file:/C:/CATALINA_BASE/webapps/teamengine/WEB-INF/classes/com/occamlab/te/earl_html_report.xsl:
  XPTY0004: A sequence of more than one item is not allowed as the first operand of '+'
```

I have investigated this error and found the problem in the earl report, in the TestRequirement we found the two elements with name `cite:testsFailed` for the same test. i.e. the main reason of the failure of report generation.

**Comment by lgoltz** [comment]
The failure occurs cause the `conformanceClass` element in the log.xml of the test  get-int-main is missing. The transformation from the log to earl results in duplicated elements because in https://github.com/opengeospatial/teamengine/blob/b6b890214b6784bbe19460bf753bdf28a9514bee/teamengine-core/src/main/java/com/occamlab/te/CtlEarlReporter.java#L233 the resource is created two times with the same name. 
The `conformanceClass` element is missing cause in 
https://github.com/opengeospatial/teamengine/blob/b6b890214b6784bbe19460bf753bdf28a9514bee/teamengine-core/src/main/java/com/occamlab/te/TECore.java#L920 this element is not written. teamengine code must be enhanced:

**Comment by lgoltz** [comment]
Fixed with https://github.com/opengeospatial/teamengine/pull/399

**Comment by dstenger** [comment]
opengeospatial/teamengine#399 was merged.

Test with TEAM Engine 5.4-SNAPSHOT and service http://ows.eox.at/cite/mapserver?service=wcs&version=2.0.1&request=getcapabilities was successful.
Now, HTML report is displayed correctly.
