### ISSUE TITLE
Skip tests requiring more than one coverage when the service provides only one

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-wcs20#79]
Affected tests are ate least:
 * wcs2:post-xml-core-req21
 * wcs2:get-kvp-core-req21
 * wcs2:soap-core-req21

Service for testing: http://ows.eox.at/cite/mapserver?service=wcs&version=2.0.1&request=getcapabilities

**Comment by keshav-nangare** [comment]
@lgoltz 

As we have fixed the describe coverage test request with multiple identifiers in PR  #69. According to PR the tests are not affected because we have iterated the for all identifiers present in response so it will add all identifiers in request whether it can be 0 or n. Before this fix the implementation is trying to access only first and last identifier due this reason the tests are failed.
