### ISSUE TITLE
Test wcs2:get-kvp-crs-req6 first listed crsSupported incompatible with coverage

### ISSUE THREAD

**Issue by coim32** [opengeospatial/ets-wcs20#97]
test case wcs2:get-kvp-crs-req6 assume the first crsSupported listed in GetCapabilities response is compatible with the first Coverage listed in GetCapabilities response.
First Coverage listed in GetCapabilities could be a GridCoverage, the assumption mentioned before will fail.
Or maybe the first crsSupported listed in GetCapabilities is incompatible with first Coverage listed in GetCapabilities like different number of dimensions
Envelop's lowerCorner and upperConrer are used to build a subset parameter with SUBSETTINGCRS as the first crsSupported listed in GetCapabilities, this assumption could be wrong making this test fail.
I'm interpreting the spec. correctly?

**Comment by ghobona** [comment]
@coim32 Please provide a link to the GetCapabilities URL of the server, to help us reproduce the issue.

**Comment by ghobona** [comment]
This question is in two parts. 

**Part 1** is:

> test case wcs2:get-kvp-crs-req6 assume the first crsSupported listed in GetCapabilities response is compatible with the first Coverage listed in GetCapabilities response.
> First Coverage listed in GetCapabilities could be a GridCoverage, the assumption mentioned before will fail.
Or maybe the first crsSupported listed in GetCapabilities is incompatible with first Coverage listed in GetCapabilities like different number of dimensions

**Part 2** is:

> Envelop's lowerCorner and upperConrer are used to build a subset parameter with SUBSETTINGCRS as the first crsSupported listed in GetCapabilities, this assumption could be wrong making this test fail.
> I'm interpreting the spec. correctly?

Regarding Part 1, the note to Requirement 4 in OGC 11-053r1 states that "This does not per se mean that every CRS reported in the Capabilities document is applicable to every coverage available from the server or to every possible trim or slice subset of such a coverage".  

Since it's not possible for the Test Suite to predict which coordinate reference systems that a server declares as supported are actually compatible with a coverage that is advertised. It is therefore necessary for the implementer to configure their WCS so that the coordinate reference systems  that are declared as supported are indeed supported for the coverages listed.

Regarding Part 2, we are still looking into it.
